version: "3.9"


services:
  postgres:
    image: postgres:12
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 2s
      retries: 3
    ports:
      - "5432:5432"

  backend:
    build:
      context: backend
    env_file: .env
    volumes:
      - ./backend/avatars:/app/avatars
      - ./backend/photos:/app/photos
    depends_on:
      postgres:
        condition: service_healthy

  auth-service:
    build:
      context: auth
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
