"""add new field to product

Revision ID: 4f55bf52d567
Revises: 3eb4a69b4a8f
Create Date: 2024-06-03 12:48:52.764874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f55bf52d567'
down_revision = '3eb4a69b4a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###